### ISSUE TITLE
bangboo语 是什么规则啊 有点好奇

### ISSUE THREAD

**Issue by coder-tq** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#1]

**Comment by WJZ-P** [comment]
bangboo语是绝区零中邦布的语言哦。哈哈，因为做的时候刚好绝区零上线那段时间玩了一会，觉得这个语言挺可爱的，所以采用了这个。后续会添加更多语种，比如喵喵语之类的。不过绝区零目前弃坑了，但是bangboo语在本项目中保留了下来
