### ISSUE TITLE
消息无法发送出去

### ISSUE THREAD

**Issue by Tanq0213** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#2]
更新2.0.5版本后普通消息无法发送出去

**Comment by WJZ-P** [comment]
是吗，我没有出现这个情况，请具体说说

**Comment by WJZ-P** [comment]
有没有截图之类的，发一下看看

**Comment by Tanq0213** [comment]
> 有没有截图之类的，发一下看看

稍等一下

**Comment by WJZ-P** [comment]
LL版本我是1.2.1,QQ版本是9.9.15-26909，你的一样吗

**Comment by Tanq0213** [comment]
> LL版本我是1.2.1，QQ版本是9.9.15-26909，你的一样吗

我跟你一样
![image](https://github.com/user-attachments/assets/ad664ca2-80a7-47b9-897b-834ad3178111)
![image](https://github.com/user-attachments/assets/6cd7d840-1fb1-4bfc-844d-a6eb4c2e7064)

**Comment by WJZ-P** [comment]
具体问题呢，一直都无法发送普通消息吗？

**Comment by Tanq0213** [comment]
> 具体问题呢，一直都无法发送普通消息吗？

是的,我刚刚又开启了插件,还是没办法发送

**Comment by WJZ-P** [comment]
怎么个没法发送法，发送按钮是灰色的吗？

**Comment by Tanq0213** [comment]
> 怎么个没法发送法，发送按钮是灰色的吗？

不是,平时发消息一样,不是灰色,也能点击发送,点击发送之后,消息会消失

**Comment by Tanq0213** [comment]
> 怎么个没法发送法，发送按钮是灰色的吗？

但是别人和自己都看不见

**Comment by Tanq0213** [comment]
> > 怎么个没法发送法，发送按钮是灰色的吗？
> 
> 但是别人和自己都看不见

好像不止普通消息,qq表情和图片都是这样,发送了但是看不见

**Comment by Tanq0213** [comment]
> > > 怎么个没法发送法，发送按钮是灰色的吗？
> > 
> > 
> > 但是别人和自己都看不见
> 
> 好像不止普通消息,qq表情和图片都是这样,发送了但是看不见

之前的版本没有出现这种情况,我在更新之后发现的

**Comment by Tanq0213** [comment]
刚刚发现,加密消息可以发送出去,哈哈

**Comment by WJZ-P** [comment]
我在尝试复现，我重装一个我自己的试试

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/fc461576-c00a-45b5-9d40-7a2ba1ddd9b8)
诶，我这是完全很正常没问题的，请问你还安装了什么别的插件吗？会不会冲突了？

**Comment by WJZ-P** [comment]
或者试试重装一下插件呢

**Comment by Tanq0213** [comment]
> ![image](https://private-user-images.githubusercontent.com/110795301/368984454-fc461576-c00a-45b5-9d40-7a2ba1ddd9b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDg2NDYsIm5iZiI6MTcyNjc0ODM0NiwicGF0aCI6Ii8xMTA3OTUzMDEvMzY4OTg0NDU0LWZjNDYxNTc2LWMwMGEtNDViNS05ZDQwLTdhMmJhMWRkZDliOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMjE5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDkwOWZlZWJhMDg0N2I1ODIyNWZmOGEwODZkMmQ5ODRlOWU5MmZlYTQyMTEyN2RjODk1YmVkYjIxNzU5YTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-1LbYTjOvAZCR_9iC-kdRqP_C3w78Ge6Isbih_JaWe0)诶，我这是完全很正常没问题的，请问你还安装了什么别的插件吗？会不会冲突了？

那应该是冲突了吧,我按照了好多插件

**Comment by WJZ-P** [comment]
下了什么，如果有涉及到修改消息的，那应该会产生冲突

**Comment by WJZ-P** [comment]
可以试试暂时把其他插件先移出plugin文件夹，然后重启QQ，功能恢复了就说明是插件冲突了

**Comment by Tanq0213** [comment]
> 可以试试暂时把其他插件先移出plugin文件夹，然后重启QQ，功能恢复了就说明是插件冲突了

![image](https://github.com/user-attachments/assets/08da6422-0dc4-44ad-9efe-d8e7da40981b)
![image](https://github.com/user-attachments/assets/4cc2e289-712c-4780-bd9d-602a690d6f3b)
![image](https://github.com/user-attachments/assets/b4129e47-3d20-44ef-9653-dd703c517857)
就这些

**Comment by WJZ-P** [comment]
哇你这装得有点多，你在版本升级之前新装过插件吗？如果没有的话，或许尝试下回退旧版本呢。就在releease里面下载2.0.4的试试能不能用

**Comment by Tanq0213** [comment]
> 哇你这装得有点多，你在版本升级之前新装过插件吗？如果没有的话，或许尝试下回退旧版本呢。就在releease里面下载2.0.4的试试能不能用

没有的,今天才更新的.好的我试试

**Comment by WJZ-P** [comment]
哦我的老天爷，这真是太奇怪了

**Comment by WJZ-P** [comment]
我看更新日志，发现了一个可能导致bug的地方，我更新了2.0.5的release包，或许你可以尝试重新装一下最新版，看看还有没有无法发送的情况。

**Comment by Tanq0213** [comment]
> 我看更新日志，发现了一个可能导致bug的地方，我更新了2.0.5的release包，或许你可以尝试重新装一下最新版，看看还有没有无法发送的情况。

真厉害,问题修复了

**Comment by WJZ-P** [comment]
好啦，没问题了(๑•̀ㅂ•́)و✧
