### ISSUE TITLE
消息阴影似乎不兼容新版qq

### ISSUE THREAD

**Issue by Starrain08** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#3]
如题
图片这些的阴影显示是没问题的，就是文字消息阴影显示有点问题
![image](https://github.com/user-attachments/assets/91e3f0b0-6eb5-4e71-aef5-5c8718813449)
![image](https://github.com/user-attachments/assets/dadde4f3-509c-43a3-9edd-4550ff95790e)

**Comment by Starrain08** [comment]
设置界面也有点不兼容
![image](https://github.com/user-attachments/assets/795ca6a9-6700-4619-85ff-3cc99d6a7d70)

**Comment by WJZ-P** [comment]
提供一下QQ版本呢，我有空看看

**Comment by WJZ-P** [comment]
还有天依这个大头挺可爱的哈哈ヽ(∀゜ )人( ゜∀)ノ

**Comment by Starrain08** [comment]
> 提供一下QQ版本呢，我有空看看

![image](https://github.com/user-attachments/assets/ef7ed4a0-d4ab-4566-a20b-8dbbef7da726)

**Comment by Starrain08** [comment]
> 还有天依这个大头挺可爱的哈哈ヽ(∀゜ )人( ゜∀)ノ

嘻嘻(●'◡'●)

**Comment by WJZ-P** [comment]
收到，修复完手头的bug之后我会尝试下载新版调试一下。你这个版本的LL是如何安装的呢？也是通过py的那个installer一键安装吗？我更新了一下readme，提供了旧版QQ和对应版本安装器的下载目录，如果有需要的话，你可以回退到readme当中的版本。那个版本显示是正常的

**Comment by Starrain08** [comment]
> 收到，修复完手头的bug之后我会尝试下载新版调试一下。你这个版本的LL是如何安装的呢？也是通过py的那个installer一键安装吗？我更新了一下readme，提供了旧版QQ和对应版本安装器的下载目录，如果有需要的话，你可以回退到readme当中的版本。那个版本显示是正常的

对，我是通过py那个installer一键安装的，当时还没有手动安装教程，暂时用这种方法，至于现在这个bug，感觉不太影响功能，退版本有点麻烦

**Comment by WJZ-P** [comment]
我已经升级到28131了。我的文本显示是正常的
![image](https://github.com/user-attachments/assets/4d245d65-2563-4d0e-add3-c00d8660d925)
可能s是和你安装的其他插件产生了冲突？

**Comment by WJZ-P** [comment]
但是这个版本我不能像你一样发送图片。我的图片不能被正确解密了

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/4f9d1bda-35af-4d4f-b099-df9553cdcd53)
这个版本似乎对图片替换加了权限检测。我的图片换不进去了。我还是换回去旧版本开发吧，这个可能要把解密图片也替换到他QQ缓存的文件夹内，比较头大
![image](https://github.com/user-attachments/assets/06f15e6b-ee49-4207-8c7a-333909ef41df)
![4dd66d03980be7196ede91edbdde9fb3](https://github.com/user-attachments/assets/45603ed2-9857-40e9-a823-f5199733f190)

**Comment by Starrain08** [comment]
> 我已经升级到28131了。我的文本显示是正常的 ![image](https://private-user-images.githubusercontent.com/110795301/378041447-4d245d65-2563-4d0e-add3-c00d8660d925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDkxODAsIm5iZiI6MTcyOTMwODg4MCwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDQxNDQ3LTRkMjQ1ZDY1LTI1NjMtNGQwZS1hZGQzLWMwMGQ4NjYwZDkyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwMzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjk4YTM3OWQ2Y2JkZWNkNGZiNWNjMmMxY2M1ODk0Mzc2MmJmNmIzNzFjZmEzNmFiMjhhMzYxZmJjNmIxOWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D08NmI_qFBewO-_HDbVbZtMTk8tMLuy12eftKRT-ZgE) 可能s是和你安装的其他插件产生了冲突？

文本还是异常的，＞﹏＜

**Comment by Starrain08** [comment]
![image](https://github.com/user-attachments/assets/2c3a3727-8542-42f0-bdfe-55b935305ee1)

**Comment by WJZ-P** [comment]
我猜是MSprint Theme的问题。禁用下快看？

**Comment by WJZ-P** [comment]
MSpring theme是一个自定义主题，我也修改了QQ样式，是可能会产生冲突的

**Comment by Starrain08** [comment]
> 我猜是MSprint Theme的问题。禁用下看看？

确实是这个问题

**Comment by WJZ-P** [comment]
行，那你禁用一下那个吧，适配的话要放后面，目前我在做EC的单独密钥功能
![eca3fce19c29415ce684969e5eb6d2eb](https://github.com/user-attachments/assets/68d68608-38d4-4f38-b783-21afcf62a093)

**Comment by Starrain08** [comment]
> 行，那你禁用一下那个吧，适配的话要放后面，目前我在做EC的单独密钥功能 ![eca3fce19c29415ce684969e5eb6d2eb](https://private-user-images.githubusercontent.com/110795301/378069953-68d68608-38d4-4f38-b783-21afcf62a093.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzI3ODEsIm5iZiI6MTcyOTMzMjQ4MSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDY5OTUzLTY4ZDY4NjA4LTM4ZDQtNGYzOC1iNzgzLTIxYWZjZjYyYTA5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDA4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2ZkZTRkMGEwNmZlYzQ0NmE5NTQ3OTE5NWNkYmVmZTE4ZjExMTcwMjdlNjU4NGEzZDdlNWFmZDdjZTIxMjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfMVfeVnqQ8-ELC7SWdpZhnIiQgWvzY_m-EbaW1O3bQ)

但文本的显示异常并不是这个插件的问题呢，我已经禁用了插件，但是没有恢复
![image](https://github.com/user-attachments/assets/ca9f45a6-d308-4d51-8848-79aa1ac22b5d)

**Comment by Starrain08** [comment]
![f15bed90f025cbeb8c75fb4996312f5f](https://github.com/user-attachments/assets/17d8c945-07cd-4eeb-8bf4-a89e7b2783aa)

**Comment by WJZ-P** [comment]
我擦，还有这种操作。我早上的时候升级到了28131，也就是你这个版本，是正常的。我不晓得是啥问题
![4dd66d03980be7196ede91edbdde9fb3](https://github.com/user-attachments/assets/a4be547e-8d5f-418a-8724-9e39011339c0)

**Comment by WJZ-P** [comment]
要不你试试把DeepL和轻量工具箱先禁用一下，看看还有没有这个问题，有的话我后面再看看

**Comment by Starrain08** [comment]
![image](https://github.com/user-attachments/assets/42aa816b-b8dc-4e6e-aa5a-1d2c794c2f53)

**Comment by WJZ-P** [comment]
哦，看来是更高的版本！那我后面升级到你这个版本看看

**Comment by Starrain08** [comment]
> 哦，看来是更高的版本！那我后面升级到你这个版本看看 ![29e0570718b97080bc289dd1993c0878](https://private-user-images.githubusercontent.com/110795301/378070823-de75c35c-84e0-4ec3-8e00-7b69af4772f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzM0MzEsIm5iZiI6MTcyOTMzMzEzMSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDcwODIzLWRlNzVjMzVjLTg0ZTAtNGVjMy04ZTAwLTdiNjlhZjQ3NzJmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk5OGJlZmU3ZTM4YWMyZTIyN2YyMGY5YTM5NjMxYjM4NGZjMzQ3ZGMzMDNhOGI4M2Q1N2QzNTRjOTM4ZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k_EE3DQP7gRd2CtasTLsvZS8MS_UsJvvdxlHyOlGwAA) [ ![29e0570718b97080bc289dd1993c0878](https://private-user-images.githubusercontent.com/110795301/378070823-de75c35c-84e0-4ec3-8e00-7b69af4772f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzM0MzEsIm5iZiI6MTcyOTMzMzEzMSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDcwODIzLWRlNzVjMzVjLTg0ZTAtNGVjMy04ZTAwLTdiNjlhZjQ3NzJmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk5OGJlZmU3ZTM4YWMyZTIyN2YyMGY5YTM5NjMxYjM4NGZjMzQ3ZGMzMDNhOGI4M2Q1N2QzNTRjOTM4ZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k_EE3DQP7gRd2CtasTLsvZS8MS_UsJvvdxlHyOlGwAA) ](https://private-user-images.githubusercontent.com/110795301/378070823-de75c35c-84e0-4ec3-8e00-7b69af4772f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzM0MzEsIm5iZiI6MTcyOTMzMzEzMSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDcwODIzLWRlNzVjMzVjLTg0ZTAtNGVjMy04ZTAwLTdiNjlhZjQ3NzJmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk5OGJlZmU3ZTM4YWMyZTIyN2YyMGY5YTM5NjMxYjM4NGZjMzQ3ZGMzMDNhOGI4M2Q1N2QzNTRjOTM4ZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k_EE3DQP7gRd2CtasTLsvZS8MS_UsJvvdxlHyOlGwAA) [ ](https://private-user-images.githubusercontent.com/110795301/378070823-de75c35c-84e0-4ec3-8e00-7b69af4772f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzM0MzEsIm5iZiI6MTcyOTMzMzEzMSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDcwODIzLWRlNzVjMzVjLTg0ZTAtNGVjMy04ZTAwLTdiNjlhZjQ3NzJmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk5OGJlZmU3ZTM4YWMyZTIyN2YyMGY5YTM5NjMxYjM4NGZjMzQ3ZGMzMDNhOGI4M2Q1N2QzNTRjOTM4ZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k_EE3DQP7gRd2CtasTLsvZS8MS_UsJvvdxlHyOlGwAA)

按你那方法禁用DEEL和轻量工具箱，加密按钮没了
![image](https://github.com/user-attachments/assets/25695254-4bb5-4d0c-be2c-53824d2c4293)

**Comment by Starrain08** [comment]
现在出现了，装了chii devtool按CTRL+R刷新后出来的

**Comment by WJZ-P** [comment]
我擦，那你按Ctrl+E试试有效不

**Comment by WJZ-P** [comment]
QQ版本高了总是偶尔会改点东西，比较麻烦。我的添加逻辑是用循环来搜索右手边的那个历史记录图标。然后自己复制一份，再改掉点击触发的功能。正常情况下应该是能用的，我自己的这个版本基本没有出现过图标消失的情况

**Comment by Starrain08** [comment]
> 我擦，那你按Ctrl+E试试有效不

没有试，现在出现了，并且发现，消息阴影恢复正常了
![image](https://github.com/user-attachments/assets/0171cdbf-0a91-4eb1-b237-929259e3fe7e)

**Comment by Starrain08** [comment]
怀疑可能是轻量的防撤回功能，因为这个功能修改了消息样式

**Comment by WJZ-P** [comment]
```
            .message-encrypted-tip-left {
                position: absolute;
                top: calc(100% + 6px);
                left: 0;
                font-size: 12px;
                white-space: nowrap;
                color: var(--text-color);
                background-color: var(--background-color-05);
                backdrop-filter: blur(28px);
                padding: 4px 8px;
                margin-bottom: 2px;
                border-radius: 6px;
                box-shadow: var(--box-shadow);
                transition: 300ms;
                transform: translateX(-30%);
                opacity: 0;
                pointer-events: none;
                color:${currentConfig.mainColor};
            }
            
            .message-encrypted-tip-right {
                position: absolute;
                top: calc(100% + 6px);
                right: 0;
                font-size: 12px;
                white-space: nowrap;
                color: var(--text-color);
                background-color: var(--background-color-05);
                backdrop-filter: blur(28px);
                padding: 4px 8px;
                margin-bottom: 2px;
                border-radius: 6px;
                box-shadow: var(--box-shadow);
                transition: 300ms;
                transform: translateX(-30%);
                opacity: 0;
                pointer-events: none;
                color:${currentConfig.mainColor};
            }
            
            .message-encrypted-tip-parent {
                border-radius: 10px;
                position: relative;
                overflow: unset !important;
                margin-top:3px;
                margin-left:3px;
                margin-right:3px;
                margin-bottom: 25px;
                box-shadow: 0px 0px 8px 5px ${currentConfig.mainColor};
            }
```
这三段css就是决定消息边框样式的。可能是其他插件对类名之类的做了修改

**Comment by WJZ-P** [comment]
> 怀疑可能是轻量的防撤回功能，因为这个功能修改了消息样式
![image](https://github.com/user-attachments/assets/8a9da9a4-9f7a-4e5c-a825-7e65d9e4aa9b)

可以直接使用单独的防撤回插件，轻量工具箱归档了，可能后面不更了。
插件商店里头搜防撤回就行

**Comment by WJZ-P** [comment]
但是高版本不知道有没有兼容性问题。我的版本下我的插件和防撤回是可以共存的。基本正常

**Comment by Starrain08** [comment]
> > 怀疑可能是轻量的防撤回功能，因为这个功能修改了消息样式
> > ![image](https://private-user-images.githubusercontent.com/110795301/378071459-8a9da9a4-9f7a-4e5c-a825-7e65d9e4aa9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzQxNDksIm5iZiI6MTcyOTMzMzg0OSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDcxNDU5LThhOWRhOWE0LTlmN2EtNGU1Yy1hODI1LTdlNjVkOWU0YWE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDMwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmEzMzcwOTZjOTdjYWU2MzE1OTQ1NzE5MjcxOTE3N2ZlMzhjNTI3MDY5NjI5NTIxMDZmMDA3ZDAwNDQ2MjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WYh2Gah2sC41jMVmD0ha6FSCP6IJAVVnHrM1EcikewI)
> 
> 可以直接使用单独的防撤回插件，轻量工具箱归档了，可能后面不更了。 插件商店里头搜防撤回就行

感觉不会跑吧，似乎要重写？

**Comment by WJZ-P** [comment]
都有可能，我们作为用户就等着看情况吧。工具箱我用得不多，不过它功能还是很多的

**Comment by Starrain08** [comment]
> 都有可能，我们作为用户就等着看情况吧。工具箱我用得不多，不过它功能还是很多的

开了工具箱又出现了那个消息阴影bug，QAQ

**Comment by WJZ-P** [comment]
> > 都有可能，我们作为用户就等着看情况吧。工具箱我用得不多，不过它功能还是很多的
> 
> 开了工具箱又出现了那个消息阴影bug，QAQ

应该是高版本的问题。我也开了工具箱，没这个毛病。后续有空再看看
![aa06c8c075330a4b63e596b92cfba2f6](https://github.com/user-attachments/assets/47a075ba-ce9c-44d7-b1a1-d7d304e490c6)

**Comment by WJZ-P** [comment]
已修复
