### ISSUE TITLE
发送加密图片，无法正常显示

### ISSUE THREAD

**Issue by InCerryGit** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#6]
发送加密图片的话，无法正常显示，需要重启QQ后才会有显示，如图：
![image](https://github.com/user-attachments/assets/5ad93e94-03b3-4768-a486-d91a6ccf477e)

重启QQ后，图片变为白色，可以双击点开
![image](https://github.com/user-attachments/assets/df97e30e-1f8b-4b38-8240-606946c5eb49)

版本详情：
![image](https://github.com/user-attachments/assets/df69b4d4-0713-4fd6-a5e2-4fb160d544fa)

**Comment by WJZ-P** [comment]
我勒个豆

**Comment by WJZ-P** [comment]
有可能是新版本API不兼容导致的。图片是裂的话说明上传失败了。但是好像又不是，毕竟你重启QQ就好了。能试试切换到其他聊天窗口再切换回来的话，会是什么情况吗？

**Comment by WJZ-P** [comment]
你看看第一个issue，他说的是消息阴影不兼容，他的版本比你的更新。不过他发图片是正常的，奇葩

**Comment by InCerryGit** [comment]
> 有可能是新版本API不兼容导致的。图片是裂的话说明上传失败了。但是好像又不是，毕竟你重启QQ就好了。能试试切换到其他聊天窗口再切换回来的话，会是什么情况吗？

重新切回聊天窗口的话，图片显示白色，可以双击点开

**Comment by InCerryGit** [comment]
> 你看看第一个issue，他说的是消息阴影不兼容，他的版本比你的更新。不过他发图片是正常的，奇葩

我刚刚升级到了最新的QQNT，问题依旧

**Comment by WJZ-P** [comment]
收到了。我这边这几天可能没办法更新。要做作业。后面我抽空看看是什么问题，如果你现在要用的话。可以尝试下载旧版本。我自己用的版本是26909，一直是正常的。版本下载地址在本项目的readme里面。有直链
![a445912afc8320f2592885253fa5c081](https://github.com/user-attachments/assets/2b4fae7f-46a5-47fa-a014-dfa13da29f67)

**Comment by WJZ-P** [comment]
哇塞，你是微软MVP吗，这个是什么头衔
![938083f97af5a1d76759bef2323450da](https://github.com/user-attachments/assets/8893fc72-80f0-45f6-8080-6b47ba0cb52c)

**Comment by WJZ-P** [comment]
26909版本是我正在使用的版本，功能一切正常。降版本的话如果Liteloader有bug可能需要删除掉整个QQ（包括Liteloader的插件目录）之后再进行安装。

还有比较坑的一点是安装了旧版本他有可能会自动给你下载新版。但是似乎装好LL之后就没有这个情况。如果你直接覆盖安装出现bug，我推荐的做法是：

**删除QQ本体的整个文件夹&Liteloader的插件文件夹（默认在C盘的文档目录下）**

**下载reamde中提供的26909QQ版本并安装**

**不要打开QQ，直接安装LL（Readme中也有python安装脚本，一键安装）**

然后再开QQ看下是否安装成功就行

**Comment by InCerryGit** [comment]
@WJZ-P  收到，感谢，我再试试

**Comment by InCerryGit** [comment]
> 哇塞，你是微软MVP吗，这个是什么头衔 ![938083f97af5a1d76759bef2323450da](https://private-user-

是的 : )

**Comment by InCerryGit** [comment]
> 收到了。我这边这几天可能没办法更新。要做作业。后面我抽空看看是什么问题，如果你现在要用的话。可以尝试下载旧版本。我自己用的版本是26909，一直是正常的。版本下载地址在本项目的readme里面。有直链 

刚刚尝试了下完全卸载以后安装26909版本，问题依旧，在朋友的电脑上试了下，图片也不行，可以后续有空再看看~

**Comment by WJZ-P** [comment]
咦，这就很奇怪了，it works on my machine

**Comment by WJZ-P** [comment]
我升级了QQ版本之后也出现了你说的这个情况。无法直接渲染出解密消息

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/2e4ac96a-4fcc-4a58-a628-e59428cccda2)
我查看输出日志。发现可能的问题是这个。在我刷新页面尝试渲染图片的时候出现了这个报错。在之前的26909版本是没有这个报错出现的

**Comment by WJZ-P** [comment]
**已找到问题并解决**

问题出在Liteloader的版本上。在旧版本的LL中，禁用了QQ的安全策略，导致可以直接进行图片替换。而最新版的LL默认没有禁用安全策略，导致原方法失效。现在已经更换为通用的LL的自定义local协议进行图片替换，不会有这个问题了。

**Comment by WJZ-P** [comment]
我再修一下其他的东西再发release

**Comment by WJZ-P** [comment]
已发布release，修复了此bug
