### ISSUE TITLE
图片消息未加密，但仍然显示解密后的效果

### ISSUE THREAD

**Issue by Starrain08** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#7]
![image](https://github.com/user-attachments/assets/9252e389-1308-46c3-b223-e2d4ab16b596)
如题

**Comment by WJZ-P** [comment]
这个也是已知bug。主要是对解密图片的判断逻辑存在漏洞造成的。后续会更新。

**Comment by WJZ-P** [comment]
![2b974419a7ba7d972f1e42bdd7ad0a57](https://github.com/user-attachments/assets/7e267126-c6d8-4160-b051-acee6befc481)

**Comment by Starrain08** [comment]
![c9fdf717292d5b622f8f6d63e3f5941c](https://github.com/user-attachments/assets/1ba746ab-01c0-4f8c-88ad-d1b4608b58e9)

**Comment by WJZ-P** [comment]
已发布新版release
