### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zaoyemitang** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#8]
是否可以添加一个只显示原消息的开关，以及在不装插件，外置的解密的小工具

**Comment by WJZ-P** [comment]
只显示原消息，意思就是不开启插件的效果吗？外置解密的小工具的话后面打算做成网站，目前还没有呐

**Comment by zaoyemitang** [comment]
嗯，是的，就是不显示成解密后的文本(=°ω°)ﾉ

**Comment by WJZ-P** [comment]
行，明天我有空加个，我差不多睡觉了

**Comment by zaoyemitang** [comment]
(๑•ૅω•´๑)晚安

**Comment by WJZ-P** [comment]
![b9a8e92b76145e2d890878093f059279](https://github.com/user-attachments/assets/2c4d9ef4-9af9-40be-bf98-6fa33a13d41a)

**Comment by WJZ-P** [comment]
已发布新版本

**Comment by zaoyemitang** [comment]
感谢喵
