### ISSUE TITLE
卸载残留

### ISSUE THREAD

**Issue by Ghostlikes** [WJZ-P/LiteLoaderQQNT-Encrypt-Chat#9]
![image](https://github.com/user-attachments/assets/fe74f061-38fa-4510-ac8f-40ef282ef1f1)
卸载完之后我的所有消息还是会出现Show Original的字样。
我尝试重新下载插件并且关闭显示原文的选项设置后仍是会出现该情况

**Comment by WJZ-P** [comment]
这不是我的插件的问题，
![94677eafeb0e93dc9cfb165ebe05f783](https://github.com/user-attachments/assets/f54e5825-a74f-470f-b6eb-523b41ac1d13)
我没有写过这个Show Original字段呀
